const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let academicYear=2569, studentToken='', adminToken='', currentStudent=null, adminTab='dashboard';
const catMeta={activities:{label:'Activities',th:'กิจกรรม / อบรม / สัมมนา'},courses:{label:'Certs-Courses',th:'รายวิชา / หลักสูตรเพิ่มเติม'},prize:{label:'Prize',th:'รางวัล / การแข่งขัน'},projects:{label:'Projects',th:'โครงงาน / ผลงาน'}};

async function rpc(fn,...args){
  document.body.classList.add('loading');
  try{
    const api=(window.SP_CONFIG&&window.SP_CONFIG.API_URL||'').trim();
    if(!api || api.includes('PASTE_GOOGLE_APPS_SCRIPT')) throw new Error('ยังไม่ได้ตั้งค่า API_URL ใน js/config.js');
    const res=await fetch(api,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:fn,args})});
    const text=await res.text();
    let data;
    try{data=JSON.parse(text)}catch{throw new Error('Backend ตอบกลับไม่ถูกต้อง กรุณาตรวจสอบ URL และสิทธิ์การ Deploy')}
    if(!data.ok) throw new Error(data.error||'เกิดข้อผิดพลาดจากระบบหลังบ้าน');
    return data.result;
  } finally { document.body.classList.remove('loading'); }
}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function showPage(id){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));window.scrollTo(0,0)}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')}
function esc(s=''){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function validHttpUrl(v=''){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)}catch{return false}}
function syncYear(){['publicYear','studentYear','adminYear'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=academicYear})}
function graduationLabel(s){if(!s.graduated)return `ม.${s.grade}`;return s.graduationStage==='m3'?'จบการศึกษา (ม.3)':'จบการศึกษา (ม.6)'}
function expiryLabel(s){return s.expiryAcademicYear?`สิ้นปีการศึกษา ${s.expiryAcademicYear}`:'-'}
function errToast(e){toast((e&&e.message)||'เกิดข้อผิดพลาด')}

$$('[data-nav]').forEach(b=>b.onclick=()=>showPage(b.dataset.nav));
$$('[data-close]').forEach(x=>x.onclick=closeModal);
$('#openRegister').onclick=openRegister; $('#openStudentLogin').onclick=openStudentLogin; $('#openAdminLogin').onclick=openAdminLogin;
$('#studentLogout').onclick=()=>{studentToken='';currentStudent=null;showPage('home')}; $('#adminLogout').onclick=()=>{adminToken='';showPage('home')};
$$('.sidebtn[data-stab]').forEach(b=>b.onclick=()=>renderStudent(b.dataset.stab));
$$('.asideAdmin').forEach(b=>b.onclick=()=>renderAdmin(b.dataset.atab));

async function init(){try{const cfg=await rpc('getPublicConfig');academicYear=Number(cfg.academicYear)||2569;syncYear()}catch(e){errToast(e)}}

function openRegister(){openModal(`<h2>สมัครสมาชิกครั้งแรก</h2><p class="muted">ใช้วันเดือนปีเกิด 8 หลักเป็นรหัสเข้าสู่ระบบ เช่น 13032548</p><div class="form-grid">
<div class="field"><label>เลขบัตรประชาชน</label><input id="rCitizen" maxlength="13" inputmode="numeric" placeholder="13 หลัก"></div>
<div class="field"><label>วันเดือนปีเกิด (DDMMBBBB)</label><input id="rDob" maxlength="8" inputmode="numeric" placeholder="13032548"></div>
<div class="field"><label>คำนำหน้า</label><select id="rTitle"><option>นาย</option><option>นางสาว</option><option>เด็กชาย</option><option>เด็กหญิง</option></select></div>
<div class="field"><label>ชื่อ</label><input id="rFirst"></div><div class="field"><label>นามสกุล</label><input id="rLast"></div>
<div class="field"><label>ชั้น</label><select id="rGrade">${[1,2,3,4,5,6].map(x=>`<option value="${x}">ม.${x}</option>`).join('')}</select></div>
<div class="field"><label>ห้อง</label><input id="rRoom" placeholder="เช่น 1"></div><div class="field"><label>เลขที่</label><input id="rNo" inputmode="numeric"></div>
<div class="field"><label>โครงการ</label><select id="rProgram"><option>MEP</option><option>MSEP</option><option>Special Program</option></select></div></div>
<div class="modal-actions"><button class="ghost" data-cancel>ยกเลิก</button><button class="primary" id="registerSubmit">สมัครสมาชิก</button></div>`);$('[data-cancel]').onclick=closeModal;$('#registerSubmit').onclick=async()=>{try{const res=await rpc('registerStudent',{citizen:$('#rCitizen').value.trim(),dob:$('#rDob').value.trim(),title:$('#rTitle').value,first:$('#rFirst').value.trim(),last:$('#rLast').value.trim(),grade:+$('#rGrade').value,room:$('#rRoom').value.trim(),no:$('#rNo').value.trim(),program:$('#rProgram').value});studentToken=res.token;currentStudent=res.student;academicYear=res.academicYear;syncYear();closeModal();toast('สมัครสมาชิกเรียบร้อย');await renderStudent('overview');showPage('studentApp')}catch(e){errToast(e)}}}

function openStudentLogin(){openModal(`<h2>เข้าสู่ระบบนักเรียน</h2><div class="form-grid"><div class="field full"><label>เลขบัตรประชาชน</label><input id="lCitizen" maxlength="13" inputmode="numeric"></div><div class="field full"><label>รหัสผ่าน (วันเดือนปีเกิด 8 หลัก)</label><input id="lDob" maxlength="8" inputmode="numeric" type="password"></div></div><div class="modal-actions"><button class="ghost" data-cancel>ยกเลิก</button><button class="primary" id="loginSubmit">เข้าสู่ระบบ</button></div>`);$('[data-cancel]').onclick=closeModal;$('#loginSubmit').onclick=async()=>{try{const res=await rpc('studentLogin',$('#lCitizen').value.trim(),$('#lDob').value.trim());studentToken=res.token;currentStudent=res.student;academicYear=res.academicYear;syncYear();closeModal();await renderStudent('overview');showPage('studentApp')}catch(e){errToast(e)}}}

function openAdminLogin(){openModal(`<h2>เข้าสู่ระบบผู้ดูแล</h2><div class="form-grid"><div class="field full"><label>Username</label><input id="aUser"></div><div class="field full"><label>Password</label><input id="aPass" type="password"></div></div><div class="modal-actions"><button class="ghost" data-cancel>ยกเลิก</button><button class="primary" id="adminSubmit">เข้าสู่ระบบ</button></div>`);$('[data-cancel]').onclick=closeModal;$('#adminSubmit').onclick=async()=>{try{const res=await rpc('adminLogin',$('#aUser').value,$('#aPass').value);adminToken=res.token;academicYear=res.academicYear;syncYear();closeModal();await renderAdmin('dashboard');showPage('adminApp')}catch(e){errToast(e)}}}

async function renderStudent(tab){if(!studentToken)return;$$('.sidebtn[data-stab]').forEach(x=>x.classList.toggle('active',x.dataset.stab===tab));const v=$('#studentView');v.innerHTML='<div class="panel"><div class="spin"></div></div>';
 try{const home=await rpc('getStudentHome',studentToken);currentStudent=home.student;academicYear=home.academicYear;syncYear();$('#studentName').textContent=`${currentStudent.title}${currentStudent.first} ${currentStudent.last}`;
 if(tab==='overview'){const c=home.counts;const continueBox=currentStudent.graduated&&currentStudent.graduationStage==='m3'?`<div class="panel continue-study"><span class="badge">สำหรับผู้จบ ม.3</span><h3>ศึกษาต่อ ม.4 โครงการห้องเรียนพิเศษ</h3><p>หากศึกษาต่อที่โครงการห้องเรียนพิเศษ โรงเรียนเทพศิรินทร์ นนทบุรี ให้ยืนยันเพื่อเปิดสถานะ ม.4 และขยายการเก็บข้อมูลถึงหลังจบ ม.6 อีก 2 ปี</p><button class="primary" id="continueM4">ศึกษาต่อ ม.4 โครงการห้องเรียนพิเศษ</button></div>`:'';v.innerHTML=`${continueBox}<div class="cards4">${Object.entries(catMeta).map(([k,m])=>`<div class="stat"><b>${c[k]||0}</b><span>${m.label}</span></div>`).join('')}</div><div class="section-title"><h3>เพิ่มข้อมูลใหม่</h3><button class="primary" id="quickAdd">+ เพิ่มรายการ</button></div><div class="cards4">${Object.entries(catMeta).map(([k,m])=>`<div class="category-card" data-addcat="${k}"><span class="badge">${m.label}</span><h3>${m.th}</h3><p>คลิกเพื่อกรอกข้อมูลรายการใหม่</p></div>`).join('')}</div>`;if($('#continueM4'))$('#continueM4').onclick=openContinueM4;$('#quickAdd').onclick=openCategoryPicker;$$('[data-addcat]').forEach(x=>x.onclick=()=>openRecordForm(x.dataset.addcat));}
 if(tab==='records'){v.innerHTML=`<div class="section-title"><h3>ข้อมูลที่เคยกรอก</h3></div><div class="cards4">${Object.entries(catMeta).map(([k,m])=>`<div class="category-card" data-viewcat="${k}"><span class="badge">${home.counts[k]||0} รายการ</span><h3>${m.label}</h3><p>${m.th}</p></div>`).join('')}</div><div id="recordList"></div>`;$$('[data-viewcat]').forEach(x=>x.onclick=()=>showStudentList(x.dataset.viewcat));}
 if(tab==='add'){v.innerHTML=`<div class="section-title"><h3>เลือกประเภทข้อมูล</h3></div><div class="cards4">${Object.entries(catMeta).map(([k,m])=>`<div class="category-card" data-addcat="${k}"><span class="badge">${m.label}</span><h3>${m.th}</h3><p>กรอกข้อมูลตามประเภทไฟล์</p></div>`).join('')}</div>`;$$('[data-addcat]').forEach(x=>x.onclick=()=>openRecordForm(x.dataset.addcat));}
 if(tab==='profile'){v.innerHTML=`<div class="panel"><div class="section-title"><h3>ข้อมูลส่วนตัว</h3></div><div class="form-grid"><div class="field"><label>เลขบัตรประชาชน</label><input value="${esc(currentStudent.citizen)}" disabled></div><div class="field"><label>คำนำหน้า</label><input value="${esc(currentStudent.title)}" disabled></div><div class="field"><label>ชื่อ</label><input value="${esc(currentStudent.first)}" disabled></div><div class="field"><label>นามสกุล</label><input value="${esc(currentStudent.last)}" disabled></div><div class="field"><label>สถานะ</label><input value="${esc(graduationLabel(currentStudent))}" disabled></div><div class="field"><label>หมดอายุ</label><input value="${esc(expiryLabel(currentStudent))}" disabled></div><div class="field"><label>ห้อง</label><input id="pRoom" value="${esc(currentStudent.room)}"></div><div class="field"><label>เลขที่</label><input id="pNo" value="${esc(currentStudent.no)}"></div><div class="field"><label>โครงการ</label><select id="pProgram"><option ${currentStudent.program==='MEP'?'selected':''}>MEP</option><option ${currentStudent.program==='MSEP'?'selected':''}>MSEP</option><option ${currentStudent.program==='Special Program'?'selected':''}>Special Program</option></select></div></div><div class="modal-actions"><button class="primary" id="profileSave">บันทึกข้อมูล</button></div></div>`;$('#profileSave').onclick=async()=>{try{const res=await rpc('updateStudentProfile',studentToken,{room:$('#pRoom').value,no:$('#pNo').value,program:$('#pProgram').value});currentStudent=res.student;toast('บันทึกแล้ว')}catch(e){errToast(e)}}}
 }catch(e){errToast(e);if(/เซสชัน/.test(e.message)){studentToken='';showPage('home')}}
}

function openCategoryPicker(){openModal(`<h2>เลือกประเภทข้อมูล</h2><div class="cards4">${Object.entries(catMeta).map(([k,m])=>`<div class="category-card" data-pick="${k}"><span class="badge">${m.label}</span><h3>${m.th}</h3></div>`).join('')}</div>`);$$('[data-pick]').forEach(x=>x.onclick=()=>{closeModal();openRecordForm(x.dataset.pick)})}

function evidenceField(){return `<div class="field full"><label>เกียรติบัตร / หลักฐาน (Google Drive URL)</label><input id="fEvidence" placeholder="https://drive.google.com/..."><small class="muted">โปรดอัปโหลดไฟล์ลง Google Drive และตั้งสิทธิ์เป็น “ทุกคนที่มีลิงก์” ก่อนนำ URL มากรอก</small></div>`}
function commonTail(){return `<div class="field"><label>ปี พ.ศ.</label><input id="fYear" type="number" value="${academicYear}"></div><div class="field"><label>ระดับ</label><select id="fLevel"><option value="school">school</option><option value="regional">regional</option><option value="national">national</option><option value="international">international</option></select></div><div class="field"><label>จำนวนชั่วโมง</label><input id="fHours" type="number" min="0"></div><div class="field"><label>ค่าสมัคร</label><input id="fFee" type="number" min="0" value="0"></div>${evidenceField()}`}
function openRecordForm(cat){const m=catMeta[cat];let body='';
 if(cat==='activities')body=`<div class="field full"><label>ชื่อกิจกรรม / โครงการ (program_title)</label><input id="fTitle"></div><div class="field"><label>บทบาท / สถานะ (exp_name)</label><input id="fExtra" value="ผู้เข้าร่วม"></div><div class="field full"><label>รายละเอียด</label><textarea id="fDescription"></textarea></div><div class="field"><label>วันที่เริ่ม</label><input id="fDate" type="date"></div><div class="field"><label>วันที่สิ้นสุด</label><input id="fEndDate" type="date"></div>${commonTail()}`;
 if(cat==='courses')body=`<div class="field full"><label>ชื่อรายวิชา / หลักสูตร (course_name)</label><input id="fTitle"></div><div class="field"><label>ระดับหลักสูตร (course_level)</label><input id="fExtra"></div><div class="field full"><label>รายละเอียด</label><textarea id="fDescription"></textarea></div><div class="field"><label>วันที่ออกผล/เกียรติบัตร</label><input id="fDate" type="date"></div><div class="field"><label>วันหมดอายุ (ถ้ามี)</label><input id="fEndDate" type="date"></div><div class="field"><label>ผลการเรียน/คะแนน</label><input id="fScore"></div><div class="field"><label>หมวดหมู่</label><input id="fCourseCategory"></div><div class="field full"><label>Reflection (ถ้ามี)</label><textarea id="fReflection"></textarea></div>${commonTail()}`;
 if(cat==='prize')body=`<div class="field full"><label>ชื่อกิจกรรม / การแข่งขัน (program_title)</label><input id="fTitle"></div><div class="field"><label>รางวัล (prize_name)</label><input id="fExtra" placeholder="เช่น รองชนะเลิศอันดับ 1"></div><div class="field full"><label>รายละเอียด</label><textarea id="fDescription"></textarea></div><div class="field"><label>วันที่เริ่ม</label><input id="fDate" type="date"></div><div class="field"><label>วันที่สิ้นสุด</label><input id="fEndDate" type="date"></div>${commonTail()}`;
 if(cat==='projects')body=`<div class="field full"><label>ชื่อโครงงาน (project_title)</label><input id="fTitle"></div><div class="field"><label>ประเภทโครงงาน (project_type)</label><input id="fExtra"></div><div class="field full"><label>รายละเอียด</label><textarea id="fDescription"></textarea></div><div class="field"><label>วันที่เริ่ม</label><input id="fDate" type="date"></div><div class="field"><label>วันที่สิ้นสุด</label><input id="fEndDate" type="date"></div>${commonTail()}`;
 openModal(`<h2>เพิ่ม ${m.label}</h2><p class="muted">ข้อมูลส่วนตัวของนักเรียนจะถูกดึงจากบัญชีอัตโนมัติ</p><div class="form-grid">${body}</div><div class="modal-actions"><button class="ghost" data-cancel>ยกเลิก</button><button class="primary" id="saveRecord">บันทึกข้อมูล</button></div>`);$('[data-cancel]').onclick=closeModal;$('#saveRecord').onclick=async()=>{try{const p={year:+$('#fYear').value,level:$('#fLevel').value,hours:$('#fHours').value,fee:$('#fFee').value,evidenceUrl:$('#fEvidence').value.trim(),description:$('#fDescription')?.value||''};if(p.evidenceUrl&&!validHttpUrl(p.evidenceUrl))throw new Error('URL หลักฐานไม่ถูกต้อง');if(cat==='activities')Object.assign(p,{programTitle:$('#fTitle').value,expName:$('#fExtra').value,date:$('#fDate').value,endDate:$('#fEndDate').value});if(cat==='courses')Object.assign(p,{courseName:$('#fTitle').value,courseLevel:$('#fExtra').value,issueDate:$('#fDate').value,expiredDate:$('#fEndDate').value,score:$('#fScore').value,courseCategory:$('#fCourseCategory').value,reflection:$('#fReflection').value});if(cat==='prize')Object.assign(p,{programTitle:$('#fTitle').value,prizeName:$('#fExtra').value,date:$('#fDate').value,endDate:$('#fEndDate').value});if(cat==='projects')Object.assign(p,{projectTitle:$('#fTitle').value,projectType:$('#fExtra').value,date:$('#fDate').value,endDate:$('#fEndDate').value});await rpc('saveStudentRecord',studentToken,cat,p);closeModal();toast('บันทึกข้อมูลเรียบร้อย');await renderStudent('overview')}catch(e){errToast(e)}}}

async function showStudentList(cat){const box=$('#recordList');box.innerHTML='<div class="panel"><div class="spin"></div></div>';try{const rows=await rpc('getStudentRecords',studentToken,cat);box.innerHTML=`<div class="panel"><div class="section-title"><h3>${catMeta[cat].label}</h3><span class="badge">${rows.length} รายการ</span></div>${rows.length?rows.map(r=>`<div class="record-item"><div><b>${esc(r.title)}</b><span>${esc(r.extra||'')}</span><small>${esc(r.year)} · ${esc(r.level||'-')}</small></div><div>${r.evidenceUrl&&validHttpUrl(r.evidenceUrl)?`<a class="evidence-link" href="${esc(r.evidenceUrl)}" target="_blank" rel="noopener">เปิดหลักฐาน</a>`:''}</div></div>`).join(''):'<div class="empty">ยังไม่มีข้อมูล</div>'}</div>`}catch(e){errToast(e)}}

function openContinueM4(){openModal(`<h2>ยืนยันการศึกษาต่อ ม.4</h2><p class="note">สำหรับนักเรียนที่จบ ม.3 และศึกษาต่อโครงการห้องเรียนพิเศษ โรงเรียนเทพศิรินทร์ นนทบุรี เท่านั้น</p><div class="field full"><label>พิมพ์ข้อความยืนยันให้ตรงกัน</label><div class="confirm-phrase">ศึกษาต่อ ม.4 โครงการห้องเรียนพิเศษ</div><input id="continuePhrase" placeholder="ศึกษาต่อ ม.4 โครงการห้องเรียนพิเศษ"></div><div class="modal-actions"><button class="ghost" data-cancel>ยกเลิก</button><button class="primary" id="continueConfirm">ยืนยันการศึกษาต่อ</button></div>`);$('[data-cancel]').onclick=closeModal;$('#continueConfirm').onclick=async()=>{try{const res=await rpc('continueM4',studentToken,$('#continuePhrase').value.trim());currentStudent=res.student;closeModal();toast(`ยืนยันแล้ว · เก็บข้อมูลถึงสิ้นปีการศึกษา ${currentStudent.expiryAcademicYear}`);await renderStudent('overview')}catch(e){errToast(e)}}}